# Generated by Django 6.0 on 2025-12-05 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('SRV', 'SRV')], max_length=10, verbose_name='Tipo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('ttl', models.IntegerField(default=3600, verbose_name='TTL')),
                ('proxied', models.BooleanField(default=False, verbose_name='Proxied (Cloudflare)')),
                ('cloudflare_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloudflare ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro DNS',
                'verbose_name_plural': 'Registros DNS',
                'ordering': ['domain', 'type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Domínio')),
                ('provider', models.CharField(default='cloudflare', max_length=50, verbose_name='Provedor')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Token')),
                ('zone_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zone ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DNSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Deletar')], max_length=20)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dns.dnsrecord')),
            ],
            options={
                'verbose_name': 'Histórico DNS',
                'verbose_name_plural': 'Históricos DNS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='dnsrecord',
            unique_together={('domain', 'type', 'name', 'content')},
        ),
    ]
