"""Create AvAdmin tables WhatsApp-first

Revision ID: 011702b420c5
Revises: 
Create Date: 2025-12-19 19:29:50.991914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011702b420c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('account_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'PASSWORD_RESET', 'MODULE_ENABLE', 'MODULE_DISABLE', 'PLAN_CHANGE', 'BILLING_UPDATE', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous values before change'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New values after change'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('is_admin_action', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', 'lifetime', name='billingcycle'), nullable=False),
    sa.Column('plan_type', sa.Enum('individual', 'business', 'enterprise', 'custom', name='plantype'), nullable=False),
    sa.Column('max_users', sa.String(), nullable=False),
    sa.Column('max_products', sa.String(), nullable=False),
    sa.Column('max_transactions', sa.String(), nullable=False),
    sa.Column('max_storage_gb', sa.String(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='\n        Features included in plan:\n        {\n            "modules": ["StockTech", "Lucrum"],\n            "whatsapp_integration": true,\n            "api_access": true,\n            "custom_branding": false,\n            "priority_support": false,\n            "advanced_analytics": false,\n            "export_data": true,\n            "multi_location": false\n        }\n        '),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('trial_days', sa.String(), nullable=False),
    sa.Column('display_order', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=True)
    op.create_table('accounts',
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('responsible_name', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('whatsapp_verified', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=8), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'cancelled', 'trial', 'pending', name='account_status'), nullable=False),
    sa.Column('client_type', sa.Enum('cliente', 'lojista', 'distribuidor', 'admin', name='client_type'), nullable=False),
    sa.Column('enabled_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="List of enabled modules: ['StockTech', 'Lucrum']"),
    sa.Column('trial_ends_at', sa.String(), nullable=True),
    sa.Column('max_users', sa.String(), nullable=False),
    sa.Column('max_products', sa.String(), nullable=False),
    sa.Column('max_transactions', sa.String(), nullable=False),
    sa.Column('current_users', sa.String(), nullable=False),
    sa.Column('current_products', sa.String(), nullable=False),
    sa.Column('current_transactions_month', sa.String(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Company-specific settings and preferences'),
    sa.Column('id', sa.String(length=14), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_cnpj'), 'accounts', ['cnpj'], unique=True)
    op.create_index(op.f('ix_accounts_company_name'), 'accounts', ['company_name'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_plan_id'), 'accounts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_accounts_whatsapp'), 'accounts', ['whatsapp'], unique=False)
    op.create_table('billing_transactions',
    sa.Column('account_id', sa.String(length=14), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'cancelled', 'refunded', 'expired', name='transaction_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('credit_card', 'debit_card', 'pix', 'boleto', 'bank_transfer', name='payment_method'), nullable=True),
    sa.Column('mercadopago_id', sa.String(length=100), nullable=True),
    sa.Column('mercadopago_status', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('pix_qr_code', sa.Text(), nullable=True),
    sa.Column('boleto_url', sa.String(length=500), nullable=True),
    sa.Column('payment_link', sa.String(length=500), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('gateway_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Metadata from payment gateway (MercadoPago response, etc.)'),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=15), nullable=True),
    sa.Column('customer_document', sa.String(length=14), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_coupon', sa.String(length=50), nullable=True),
    sa.Column('gateway_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_trial_conversion', sa.Boolean(), nullable=False),
    sa.Column('is_upgrade', sa.Boolean(), nullable=False),
    sa.Column('is_renewal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_transactions_account_id'), 'billing_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_billing_transactions_created_at'), 'billing_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_transactions_id'), 'billing_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_billing_transactions_invoice_number'), 'billing_transactions', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_billing_transactions_mercadopago_id'), 'billing_transactions', ['mercadopago_id'], unique=False)
    op.create_index(op.f('ix_billing_transactions_paid_at'), 'billing_transactions', ['paid_at'], unique=False)
    op.create_index(op.f('ix_billing_transactions_plan_id'), 'billing_transactions', ['plan_id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=14), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'manager', 'user', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_whatsapp'), 'users', ['whatsapp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_billing_transactions_plan_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_paid_at'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_mercadopago_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_invoice_number'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_created_at'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_account_id'), table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_index(op.f('ix_accounts_whatsapp'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_plan_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_company_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_cnpj'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
