"""Add missing user fields

Revision ID: f9cf70b8dcbc
Revises: 011702b420c5
Create Date: 2026-01-16 02:39:03.059725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9cf70b8dcbc'
down_revision: Union[str, None] = '011702b420c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=11), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.Enum('whatsapp_login', 'password_reset', 'phone_verification', name='verificationcodetype'), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('address_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('reference_point', sa.String(), nullable=True))
    op.add_column('users', sa.Column('store_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('facade_photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_street', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('address_city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address_state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_count',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'manager', 'user', 'viewer', name='user_role'),
               type_=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', 'VIEWER', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'address_state')
    op.drop_column('users', 'address_city')
    op.drop_column('users', 'address_street')
    op.drop_column('users', 'facade_photo_url')
    op.drop_column('users', 'logo_url')
    op.drop_column('users', 'store_name')
    op.drop_column('users', 'reference_point')
    op.drop_column('users', 'address_number')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'complement')
    op.drop_column('users', 'birth_date')
    op.alter_column('accounts', 'status',
               existing_type=sa.Enum('active', 'suspended', 'cancelled', 'trial', 'pending', name='account_status'),
               type_=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'CANCELLED', 'TRIAL', 'PENDING', name='accountstatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
