# Generated by Django 6.0 on 2025-12-05 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Trabalho')),
                ('task_type', models.CharField(choices=[('restart_frontend', 'Reiniciar Frontend'), ('restart_backend', 'Reiniciar Backend'), ('restart_container', 'Reiniciar Container'), ('backup_database', 'Backup de Banco de Dados'), ('cleanup_logs', 'Limpar Logs'), ('custom_command', 'Comando Customizado')], max_length=50, verbose_name='Tipo de Tarefa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data/Hora Agendada')),
                ('recurrence', models.CharField(choices=[('once', 'Uma vez'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente'), ('custom', 'Personalizado (Cron)')], default='once', max_length=20, verbose_name='Recorrência')),
                ('cron_expression', models.CharField(blank=True, help_text='Ex: 0 2 * * * (diariamente às 2h)', max_length=100, null=True, verbose_name='Expressão Cron')),
                ('container_name', models.CharField(blank=True, help_text='Obrigatório para tarefas de container', max_length=255, null=True, verbose_name='Nome do Container')),
                ('custom_command', models.TextField(blank=True, help_text='Comando a ser executado (para tipo Customizado)', null=True, verbose_name='Comando Customizado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendado'), ('running', 'Em Execução'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Execução')),
                ('run_count', models.IntegerField(default=0, verbose_name='Número de Execuções')),
                ('last_result', models.TextField(blank=True, null=True, verbose_name='Resultado da Última Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabalho Agendado',
                'verbose_name_plural': 'Trabalhos Agendados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendado'), ('running', 'Em Execução'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='running', max_length=20)),
                ('output', models.TextField(blank=True, null=True, verbose_name='Saída')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='crons.scheduledtask')),
            ],
            options={
                'verbose_name': 'Execução de Tarefa',
                'verbose_name_plural': 'Execuções de Tarefas',
                'ordering': ['-started_at'],
            },
        ),
    ]
