# Generated by Django 6.0 on 2025-12-05 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('service', models.CharField(choices=[('cloudflare', 'Cloudflare'), ('stripe', 'Stripe'), ('whatsapp', 'WhatsApp'), ('google_maps', 'Google Maps'), ('mercadopago', 'Mercado Pago'), ('other', 'Outro')], max_length=50, verbose_name='Serviço')),
                ('key_hash', models.CharField(max_length=255, verbose_name='Hash da Key')),
                ('key_last4', models.CharField(max_length=4, verbose_name='Últimos 4 caracteres')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('scopes', models.TextField(blank=True, null=True, verbose_name='Escopos/Permissões')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='apikeys.apikey')),
            ],
            options={
                'verbose_name': 'Uso de API Key',
                'verbose_name_plural': 'Usos de API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
